package co.kaush.usf

import kotlinx.coroutines.*
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.*
import kotlin.coroutines.cancellation.CancellationException

/**
 * When building features, we create <Feature>ViewModelImpl.kt classes that extend this class. and
 * only implement the relevant parts of the feature. All boilerplate code is handled by
 * [UsfViewModelImpl] & the corresponding <Feature>UsfViewModel] class generated by the annotation
 * processor.
 */
@OptIn(ExperimentalCoroutinesApi::class)
abstract class UsfViewModelImpl<E : Any, R : Any, VS : Any, Effect : Any, LocalState : Any?>(
    initialState: VS,
    private val coroutineScope: CoroutineScope,
    private val processingDispatcher: CoroutineDispatcher = Dispatchers.IO,
    private val logger: UsfVmLogger =
        object : UsfVmLogger {
            val tag = Thread.currentThread().stackTrace[4].className.split(".")
                .last() // TODO: switch to something like logcat

            override fun debug(message: String) = run { /*do something*/ }
            override fun warning(message: String) = run { /*do something*/ }
            override fun error(error: Throwable, message: String) = run { /*do something*/ }
        }
) : UsfVm<E, VS, Effect> {

    val handler: CoroutineExceptionHandler = CoroutineExceptionHandler { _, e ->
        logger.error(e, "\uD83D\uDC80 uncaught exception in a child coroutine")
    }

    /**
     * @param event every input is transformed into an [E] and fed into the VM by the Screen
     * @return [Flow]<[R]> a single [E] can result in multiple [R]s for e.g. emit a
     *   Result for loading and another for the actual result
     */
    protected abstract suspend fun eventToResultFlow(event: E): Flow<R>

    /**
     * @param currentViewState the current [VS]tate of the view (.copy it for the returned [VS]tate)
     * @return [VS]tate Curiously, we don't return a [Flow]<[VS]> here every [R]esult will only ever
     *   be transformed into a single [VS]tate if you want multiple [VS]tates emit multiple [R]esults
     *   transforming each [R]esult to the respective [VS]tate
     */
    protected abstract fun resultToViewState(currentViewState: VS, result: R): VS

    /**
     * @param result a single [R]esult can result in multiple [Effect]s for e.g. emit a VE for
     *   navigation and another for an analytics call hence a return type of [Flow]<[Effect]>
     * @return [Flow] of [Effect]s where null emissions will be ignored automatically
     */
    protected abstract fun resultToEffects(result: R): Flow<Effect>

    /*
     * - Using a `Channel` allows us to buffer events emitted before the flow has started collecting.
     *
     *  This setup ensures that events are not lost if they are sent before the internal collector
     *   starts, and multiple events can be buffered until they are processed.
     */
    private val _events = Channel<E>(10)

    /*
     * The `_viewState` holds the latest `ViewState` and replays it to new subscribers.
     */
    private val _viewState = MutableStateFlow(initialState)
    override val viewState: StateFlow<VS> = _viewState.asStateFlow().logViewStateEmission()

    /*
       * - Using a `Channel` ensures once a value is exhausted, it won't be consumed again.
       */
    private val _effects = Channel<Effect>()
    override val effects: Flow<Effect> = _effects.receiveAsFlow()

    /*
     * Lazy pipeline setup that will be initialized on first event
     */
    private val pipeline = lazy {
        _events
            .receiveAsFlow()
            .flatMapMerge { event ->
                try {
                    eventToResultFlow(event)
                } catch (e: Exception) {
                    if (e is CancellationException) throw e // propagate cancellation
                    logger.error(e, "[ev →  r] \uD83D\uDC80 on $event")
                    emptyFlow()
                }
            }
            .onCompletion { logger.debug("[ev →  r] ✗") }
            .flowOn(processingDispatcher) // ensure upstream runs on processingDispatcher
            .onEach { rslt ->
                try {
                    // logger.debug("[ev →  r] ${rslt.javaClass.simpleName}") // too noisy for prod

                    // do conversion in processingDispatcher but emit back on main thread
                    // (might be an over-optimization)
                    val vs = withContext(processingDispatcher) {
                        resultToViewState(
                            _viewState.value,
                            rslt
                        )
                    }
                    _viewState.emit(vs)

                    resultToEffects(rslt)
                        .flowOn(processingDispatcher)
                        .catch { logger.error(it, "[r  → ef] \uD83D\uDC80") }
                        .onEach { effect ->
                            logger.debug("[ef →   ] ${effect.javaClass.simpleName}")
                            _effects.send(effect)
                        }
                        .launchIn(coroutineScope + handler)
                } catch (e: Exception) {
                    if (e is CancellationException) throw e // propagate cancellation
                    logger.error(e, "[r  →  *] \uD83D\uDC80 onEach")
                }
            }
            // catch exceptions upstream otherwise not caught, including ones unhandled in onEach
            .catch { e -> logger.error(e, "[ev →  *] \uD83D\uDC80 ✗") }
            .launchIn(coroutineScope + handler)
    }

    init {
        logger.debug("[  VM   ] \uD83D\uDC76 on ${Thread.currentThread().name}")
    }

    open fun getLocalState(): LocalState? = null

    override fun processInput(event: E) {
        coroutineScope.launch(handler) {
            pipeline.value // Initialize pipeline on first event
            _events.send(event)
            withContext(processingDispatcher) { logger.debug("[ev →   ] ${event.javaClass.simpleName}") }
        }
    }


    /**
     * Creates a parallel flow chain for logging ViewState emissions and can be slapped on an existing
     * StateFlow
     *
     * The separate flow chain leverages StateFlow's distinctUntilChanged() behavior, meaning logging
     * only occurs when the ViewState actually changes.
     *
     * @return The original StateFlow, unmodified
     */
    private fun <ViewState : Any> StateFlow<ViewState>.logViewStateEmission(): StateFlow<ViewState> {
        onEach { logger.debug("[vs →   ] ${viewState.javaClass.simpleName}") }
            .flowOn(processingDispatcher)
            .launchIn(coroutineScope)
        return this
    }

    interface UsfVmLogger {
        fun debug(message: String)

        fun debugEvents(event: Any, message: String? = null) =
            debug(message ?: "----- [E] ${Thread.currentThread().name} $event")

        fun debugResults(result: Any, message: String? = null) =
            debug(message ?: "----- [result] ${Thread.currentThread().name} $result")

        fun debugViewState(viewState: Any, message: String? = null) =
            debug(message ?: "----- [view-state] ${Thread.currentThread().name} $viewState")

        fun debugSideEffects(effect: Any, message: String? = null) =
            debug(message ?: "----- [effect] ${Thread.currentThread().name} $effect")

        fun warning(message: String)

        fun error(error: Throwable, message: String)
    }
}
